# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Converra'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.png'
- name: LOGO
  value: '/brand-assets/logo.png'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.png'
- name: BRAND_URL
  value: 'https://converra.samabrains.com'
- name: WIDGET_BRAND_URL
  value: 'https://converra.samabrains.com'
- name: BRAND_NAME
  value: 'Converra'
- name: TERMS_URL
  value: 'https://converra.samabrains.com/terms'
- name: PRIVACY_URL
  value: 'https://converra.samabrains.com/privacy'
- name: DISPLAY_MANIFEST
  value: false
# ------- End of Branding Related Config ------- #
